agent_name = "simple-voicebot"
image = "your-docker-hub-username/simple-voicebot:0.1"
image_credentials = "your-dockerhub-creds"
secret_set = "simple-voicebot-secrets"
enable_krisp = true

[scaling]
min_instances = 0
